{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "status", "query": { "query": "label_values(status)" } }
  ]
 },
 "panels": [
  {
   "title": "Target Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} ({{instance}})" }
   ]
  },
  {
   "title": "API tasks done",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 3 },
   "targets": [
    { "expr": "task_api_tasks_done", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API tasks total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 7 },
   "targets": [
    { "expr": "task_api_tasks_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP 2xx,4xx,5xx requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"2..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(http_requests_total{status=~\"4..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 11 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}