name: Promote Image

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'Existing image tag'
        required: true
        type: string

      release_tag:
        description: 'New release tag'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  promote:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull source image
        run: |
          docker pull \
            "${REGISTRY}/${IMAGE_NAME}:${{ inputs.source_tag }}"

      - name: Tag release image
        run: |
          docker tag \
            "${REGISTRY}/${IMAGE_NAME}:${{ inputs.source_tag }}" \
            "${REGISTRY}/${IMAGE_NAME}:${{ inputs.release_tag }}"

      - name: Push release image
        run: |
          docker push \
            "${REGISTRY}/${IMAGE_NAME}:${{ inputs.release_tag }}"
